# Generated by Django 4.0.4 on 2022-06-20 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
