# Generated by Django 4.0.4 on 2022-06-29 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0003_alter_marca_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalcientifico',
            name='apellido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='personalcientifico',
            name='legajo',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personalcientifico',
            name='nombre',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tiporecursotecnologico',
            name='recursoTecnologico',
            field=models.ManyToManyField(blank=True, null=True, to='reservaRT.recursotecnologico'),
        ),
    ]
