# Generated by Django 4.0.4 on 2022-06-29 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0005_alter_recursotecnologico_cambioestadorecursotecnologico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recursotecnologico',
            name='fechaBaja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
