# Generated by Django 4.0.4 on 2022-06-29 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0006_alter_recursotecnologico_fechabaja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='centroinvestigacion',
            name='asignacionCientifico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservaRT.asignacioncientifico'),
        ),
        migrations.AlterField(
            model_name='centroinvestigacion',
            name='fechaBaja',
            field=models.DateField(blank=True, null=True),
        ),
    ]
