# Generated by Django 4.0.4 on 2022-06-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0008_alter_asignacioncientifico_fechahasta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignacioncientifico',
            name='personalCientifico',
        ),
        migrations.AddField(
            model_name='asignacioncientifico',
            name='personalCientifico',
            field=models.ManyToManyField(to='reservaRT.personalcientifico'),
        ),
    ]
