# Generated by Django 4.0.4 on 2022-07-02 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0009_remove_asignacioncientifico_personalcientifico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='turno',
            name='cambioEstadoTurno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservaRT.cambioestadoturno'),
        ),
    ]
