# Generated by Django 4.0.4 on 2022-07-02 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0010_alter_turno_cambioestadoturno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestadoturno',
            name='fechaHoraHasta',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
