# Generated by Django 4.0.4 on 2022-07-02 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0011_alter_cambioestadoturno_fechahorahasta'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AsignacionCientifico',
            new_name='AsignacionCientificoDelCI',
        ),
    ]
