# Generated by Django 4.0.4 on 2022-07-03 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0012_rename_asignacioncientifico_asignacioncientificodelci'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambioestadoturno',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservaRT.estado'),
        ),
        migrations.AlterField(
            model_name='cambioestadoturno',
            name='fechaHoraDesde',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
