# Generated by Django 4.0.4 on 2022-07-03 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0013_alter_cambioestadoturno_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='turno',
            name='cambioEstadoTurno',
        ),
        migrations.AddField(
            model_name='turno',
            name='cambioEstadoTurno',
            field=models.ManyToManyField(blank=True, null=True, to='reservaRT.cambioestadoturno'),
        ),
    ]
