# Generated by Django 4.0.4 on 2022-07-03 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservaRT', '0014_remove_turno_cambioestadoturno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambioestadort',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reservaRT.estado'),
        ),
    ]
